### ISSUE TITLE
Make install error on Ubuntu 18.04

### ISSUE THREAD

**Issue by RevanthRajashekar** [sedcli/sedcli#11]
make install throws an error on Ubuntu 18.04 (any kernel version)
The attached screenshot explains all:
![Error_Make_install_sedcli](https://user-images.githubusercontent.com/39538162/67712590-e8052d80-f989-11e9-8c29-cf9607676262.PNG)

**Comment by AndrzejJakowski** [comment]
Hi Revanth, 

Could you please check if #13 fixes that problem?

**Comment by AndrzejJakowski** [comment]
Closing the issue
