### ISSUE TITLE
Issues found by static code analyzer

### ISSUE THREAD

**Issue by oshchirs** [sedcli/sedcli#29]
An analysis made with clang static analyzer found several minor issues in the libsed:

Bug Group|	Bug Type ▾|	File|	Function/Method|	Line|	Path Length	|
------------ | ---------------|--------|--------------------|------|-------------|
Dead store|	Dead assignment|	nvme_pt_ioctl.c|	opal_setup_global_range_pt|	1185|	1	|
Logic error|	Uninitialized argument value|	nvme_pt_ioctl.c|	opal_eraselr_pt|	2031|	8	|
Logic error|	Uninitialized argument value|	nvme_pt_ioctl.c|	opal_setuplr_pt|	1890|	10|

Full report is attached.  [scan-build-2020-02-13-151451-28687-1.zip](https://github.com/sedcli/sedcli/files/4215487/scan-build-2020-02-13-151451-28687-1.zip)

**Comment by RevanthRajashekar** [comment]
This has been fixed in https://github.com/sedcli/sedcli/pull/30/files
