### ISSUE TITLE
Introduce more tests for sedcli utility

### ISSUE THREAD

**Issue by AndrzejJakowski** [sedcli/sedcli#5]
It would be great to have more functional tests for sedcli utility. I was thinking about following tests:
1. Initial provision with randomly generated SID password
2. read lock disk, try reading data, try writing data
3. write lock disk, try reading data, try writing data
4. unlock disk try reading data, try writing data
5. change Admin1 password and repeat steps 2-4
6. perform revert tper using SID password
7 perform revert tper using PSID password

**Comment by RevanthRajashekar** [comment]
will do it :)

**Comment by AndrzejJakowski** [comment]
Implemented with #10 pull request
