### ISSUE TITLE
sed_init + sed_deinit + sed_init segfaults

### ISSUE THREAD

**Issue by after5cst** [sedcli/sedcli#75]
The problem is that sed_deinit in opal_parser.c forgets to reset the global free_token_list.next to NULL.  As a result, the free token list points to freed memory, and on the next sed_init it attempts to grab a token during the process.
Fix is simple enough in opal_parser_deinit():
```C
void opal_parser_deinit(void)
{
	if (token_storage != NULL) {
		free(token_storage);
		token_storage = NULL;
	}
	free_token_list.next = NULL;  // THIS LINE ADDED
}
```

**Comment by RevanthRajashekar** [comment]
@after5cst thank you for reporting the issue.
@AndrzejJakowski  thanks for the patch  [648e185](https://github.com/sedcli/sedcli/commit/648e185c23fec2664629f97d76e1d8855e4e5df6) that fixes the issue now.
