### ISSUE TITLE
Level0 discovery reports incorrect CNL feature values

### ISSUE THREAD

**Issue by RevanthRajashekar** [sedcli/sedcli#81]
In function **copy_cnl_feat**, the usage of **be32toh** provides incorrect values for CNL feature.
 
Current output:
Maximum Key Count  : -2147483648
Unused Key Count : 2130706432

By removing the be32toh, we get the correct values:
Correct output:
Maximum Key Count : 128
Unused Key Count : 127

**Comment by AndrzejJakowski** [comment]
TCG Storage Architecture Core Specification specifies in chapter "3.2.2.2 Endianness" that integers transmitted across the interface are big endian.  The be32toh call looks correct to me. It looks to me like device issue.

**Comment by utpalsolanki** [comment]
@AndrzejJakowski  @RevanthRajashekar 
This was actually fixed to be aligned with specs here https://github.com/sedcli/sedcli/pull/73/files
If you have tried this with one of CNL supported Intel SSD, it might have this as a firmware bug.

After https://github.com/sedcli/sedcli/pull/73/files fix, SedCli should be working as per big endian format.

**Comment by AndrzejJakowski** [comment]
Cool. thx for letting us know
